Vagrant.configure("2") do |config|
  config.vm.box = "altafsaljooq/EndeavousOS"
  config.vm.box_version = "0.4"
  config.ssh.insert_key = false

   config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Change name to avoid conflict
    vb.name = "myAarchExperiment03"  
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.memory = 16384
    config.ssh.private_key_path = "private_key"
  end
  
end

