Vagrant.configure("2") do |config|
  config.vm.box = "AarchExp"
  config.ssh.insert_key = false

   config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    vb.name = "myAarchExperiment01"

    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

    vb.customize ['modifyvm', :id, '--drag-and-drop', 'bidirectional']

    config.ssh.private_key_path = "private_key"

  end
end

